[this file is written in orgmode markeup]

wrf_install is collection of shell scripts to automate the processing
of downloading and building wrf model and its dependencies on veriety of
machines with different compilers.

Website: https://github.com/yyr/wrf_install

* Introduction
Building wrf model is tedious. These are bunch of shell scripts to
automate the downloading and building process. these scripts are very
much workable state. This is first written by Rick Morgans.

I have successfully built (automated)
- on UBUNTU with both gcc and intel compilers
- on SGI altix with  gcc and intel

* How to Use
** quick read
start with sourcing the SOURCEME file. By default building process
will be in ~ ~/wrf ~ directory. Edit this if you want to change
the location of the building. set the compiler option aswell.
and source the file.

: source SOURCEME

once this is done.  download and extract all the packages we need by
calling the script ~download_app.sh~

: ./download_app.sh ALL

the packages are downloaded and extracted in ~/wrf/src directory.

and go to the build directory. start building the each by calling
individual ~.sh~ file or to install all at once call ~ALL.sh~

: cd build
: ./ALL.sh

** little walk through
To test how it works..

try to install one component.. Follow these steps.

open the SOURCEME file with your editor
you may want to customize these options;
- location of install (WRF_BASE variable)
  by default ~/wrf is the folder all the downloads and installation takes place.

- which compilers you want to use
  by default it is intel. if you have GNU gcc instead of intel
  compilers. change them accordingly.  (there is an example how to set ,
  it must be easy)

OKAY now lets try to install zlib first

#+BEGIN_SRC sh
. SOURCEME # this is where you start
./download_app.sh ZLIB # download zlib and decompress it
cd build # goto the directory where build scripts are located
./ZLIB.sh
#+END_SRC

that's it.. if everything goes well you have just installed zlib. see
in the $WRF_BASE directory.

I strongly *suggest* you to install the components one by one at the first
time.. So its easy for you to see what is going on..

these are the components you can install.(each one has its ?.sh file
in the build directory)

- ZLIB
- SZIP
- JPEG
- JASPER
- HDF5
- UDUNITS2
- NETCDF4
- NCVIEW
- MPICH
- WRF
- WPS

* Contributing
I welcome any patches/reports/suggestions. Drop [[mailto:yagensh◎live.com][me]] a mail (replace
Unicode character) or report on github repository.

https://github.com/yyr/wrf_install/issues

please report any problems or

* Compilers
the compilers are available for me at work. So
** gcc, gfotran
works by default (my need minor changes)
** intel
works by default (my need minor changes)
** pgf & sgi
not tested; would be easy to support this I think.
** aix & ibm compiler
not yet used

* system wide (mostly with gcc not all the components)

* faq
check ~faq.org~ file in ~doc~ folder

* TODO next
** building individual component by resolving the dependencies
dependency resolving is not possible right now.. you need to install
the specific order..

** build on aix machine sr110000 with IBM compiler
** allow customizations for which packages to install
right now these are tightly coupled
